blank_issues_enabled: false
contact_links:
  - name: ğŸ“– ä½¿ç”¨èªªæ˜
    url: https://github.com/garyellow/ntpu-linebot-go#-ä½¿ç”¨æ•™å­¸
    about: æŸ¥çœ‹æ©Ÿå™¨äººä½¿ç”¨æ•™å­¸
  - name: ğŸ’¬ åŠ å…¥å¥½å‹
    url: https://lin.ee/QiMmPBv
    about: ç›´æ¥åœ¨ LINE ä¸­ä½¿ç”¨æ©Ÿå™¨äºº
